jwt:
  secret: ${JWT_SECRET}

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
  port: ${CONTAINER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  datasource:
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.${DB_DIALECT}
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.${DB_DIALECT}
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

ui:
  app:
    url: ${UI_APP_URL}

application:
  title: Spiritual Center
  version: 1.0

mytwilio:
  FROM_NUMBER: ${SECRET_FROM_NUMBER}
  SID_KEY: ${SECRET_SID_KEY}
  TOKEN_KEY: ${SECRET_TOKEN_KEY}