jwt:
  secret: ${JWT_SECRET}

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: NATIVE

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.${DB_DIALECT}
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.${DB_DIALECT}
        format_sql: true
    open-in-view: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

mytwilio:
  FROM_NUMBER: ${SECRET_FROM_NUMBER}
  SID_KEY: ${SECRET_SID_KEY}
  TOKEN_KEY: ${SECRET_TOKEN_KEY}