spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
ui:
  app:
    url: ${UI_APP_URL}
application:
  title: Spiritual Center
  version: 1.0

jwt:
  secret: ${JWT_SECRET}

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
  port: ${CONTAINER_PORT:8080}

mytwilio:
  FROM_NUMBER: ${FROM_NUMBER}
  SID_KEY: ${SID_KEY}
  TOKEN_KEY: ${TOKEN_KEY}